### ISSUE TITLE
Windows 默认使用的是全局的 tsc，而不是项目 node_modules 里的 tsc

### ISSUE THREAD

**Issue by pilaoda** [midwayjs/mwtsc#29]
能否改成优先使用项目 node_modules 里的 tsc ？

**Comment by pilaoda** [comment]
有时候全局和项目使用的 ts 版本不一样

**Comment by czy88840616** [comment]
已经指定了 cwd，应该就是当前项目找的吧

https://github.com/midwayjs/mwtsc/blob/main/lib/process.js#L21

**Comment by pilaoda** [comment]
> 已经指定了 cwd，应该就是当前项目找的吧
> 
> https://github.com/midwayjs/mwtsc/blob/main/lib/process.js#L21

cwd 是启动后进程的cwd，实际上执行的命令是 `C:\\...\cmd.exe tsc.cmd ...`
有空测一下就知道了

**Comment by pilaoda** [comment]
得加一个npx `npx tsc`，才会在当前目录里找

**Comment by czy88840616** [comment]
> > 已经指定了 cwd，应该就是当前项目找的吧
> > https://github.com/midwayjs/mwtsc/blob/main/lib/process.js#L21
> 
> cwd 是启动后进程的cwd，实际上执行的命令是 `C:\\Windows\\system32\\cmd.exe tsc.cmd ...` 有空测一下就知道了

没有 windows 环境，这才是最难的

**Comment by czy88840616** [comment]
> 得加一个npx `npx tsc`，才会在当前目录里找

可能得把 tsc.cmd 拼成绝对路径

**Comment by czy88840616** [comment]
看看新版本是否可以了

**Comment by pilaoda** [comment]
可以了
